#!/usr/local/bin/gosh
(use gauche.parseopt)
(use taskf.cmd)
(define (main args)
  (let-args (cdr args)
			((w "w|write" => w)
			 (r "r|read" => r)
			 (d "d|del" => del))
			(clear)
			(print "YES,TaskList!!!!!!!!")
			(print "-------------------")
			(ToDo)))
